# Generated by Django 4.1.5 on 2023-02-23 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swapoperationsapp', '0002_delete_swapoperations'),
        ('albumapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Catalogue',
        ),
    ]
